name: CICD

on:
  push:
    branches: [deploy-to-ec2]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: build project
        run: mvn clean install -DskipTests
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build docker image
        run:  docker build -t ismaelmours/lotto-number-generator .
      - name: Publish image to docker hub
        run: docker push  ismaelmours/lotto-number-generator:latest
        
        
        
  deploy:
    needs: build
    runs-on: [awsec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull ismaelmours/lotto-number-generator:latest
      - name: Delete old containers
        run: docker rm -f lotto-number-generator-container
      - name: Run docker container
        run: docker run -d  -p 8080:8080 --name lotto-number-generator-container ismaelmours/lotto-number-generator:latest
        
        
