name: CICD

on:
  push:
    branches: [deploy-to-ec2]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: build project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build docker image
        run:  docker build -t IsmaelMours/lotto-number-generator .
      - name: Publish image to docker hub
        run: docker push IsmaelMours/lotto-number-generator:latest
        
        
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull IsmaelMours/lotto-number-generator:latest
      - name: Delete old container
        run: docker rm -f lotto-number-generator-container
      - name: Run docker container
        run: docker run -d  -p 8080:8080 --name lotto-number-generator-container IsmaelMours/lotto-number-generator:latest
        
        
